# Site settings
title: Iknow-Album
description: Hi 🖐
baseurl: "/iknow-album" # the subpath of your site, e.g. /blog
url: "https://iknowkis.github.io" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/iknowkis
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
